all: ej1 ej2 ej3 ej4 ej5 ej7

ej1: ej1.c
	gcc -Wall -o ej1 ej1.c -lpcap

ej2: ej2.c
	gcc -Wall -o ej2 ej2.c -lpcap

ej3: ej3.c
	gcc -Wall -o ej3 ej3.c -lpcap

ej4: ej4.c
	gcc -Wall -o ej4 ej4.c -lpcap

ej5: ej5.c
	gcc -Wall -o ej5 ej5.c -lpcap

ej7: ej7.c
	gcc -Wall -o ej7 ej7.c -lpcap

clean:
	-\rm -f ej1 ej2 ej3 ej4 ej5 ej7

mrproper: clean
